### PR TITLE
Style changes to the FightSummary area

### PR DESCRIPTION
**Pull request by samuelhaydnarmstrong**
- General style changes to the FightSummary area.  Cleared up some of the wording, changed links to icons, general simplification, and some colour changes.
- StrikeLink only shows when you've got a strike to undo.
- Made some of the buttons a little more obvious.

image
image

I appreciate that it's a bit of a deviation from the styling of the rest of the GUI, but kept the same red and blue that the map uses.  Happy to adjust as you'd like.

### CODE REVIEW

**Comment by xrabohrok** [comment]
Hey, thanks for the pull request!  I really really like what you have done here, and it is pretty cool to look at.  I've gone ahead and pre-staged a rebase merge on a branch called `sam-main` that includes some stuff I hadn't pushed up yet at the time, future changes should be done there.

Only a couple observations:

1. I've been trying to be very conscious of the use of red and blue since they are team colors, which is why a lot of the icons are strange greens or purples.  Instead of match losers being red, I'm wondering if greying them out might avoid any potential confusion.
2. The link icons could probably stand to be bigger overall, especially when they get used elsewhere.

Other than that, just let me know if you would like to adjust those yourself or let me know if I should take a swing at it.

Thanks again!

**Comment by samuelhaydnarmstrong** [comment]
Hey no worries!  Thanks for reviewing so quickly.

Both those points make sense to me; you're definitely right that the icons could do with being a bit more 'pride of place'.  I can pick both of those up after work tomorrow :)

- [x] Change win/loss colours to green and grey.
- [x] Make icons more prominent (and have a think how to make them more obvious without putting the app names back in)

**Comment by samuelhaydnarmstrong** [comment]
In the latest commit I've:
- Increased the size of the icons, hopefully they should now be far clearer.
- Removed the red defeat box and replaced it with a grey one (with a small blood animation to make the loss clear!)

image

As always let me know what you think and I'm happy to make changes.  Equally clear that this probably won't be the final version, happy to keep tweaking it over time.

**Comment by xrabohrok** [comment]
I like this, I'll merge it in once I'm done with this kinda intense refactor.

**Comment by xrabohrok** [comment]
The merge conflicts as shown above are fairly trivial to resolve, some css classes landed on each other and in most other cases your changes can be accepted as is.

Of bigger issue is that a lot of the styles don't translate to mobile well (which is what I've been working on), and some of my overall adjustments (mostly converting size defs from em to either vw/vh or percents) have knocked around the positions of the boxes.  It _almost_ works on mobile, but the pixel positions don't work right on some devices.

I can work to convert this on my side or you can take a swing, just let me know.

**Comment by xrabohrok** [comment]
Branch has been merged through rebase (Github is bad at detecting those), but also has been heavily edited so that it it scales reactively properly.  I learned a lot doing this, and it looks good, thanks for the contribution!

**Pull request closed without merging**
